### ISSUE TITLE
如何使用打字机效果

### ISSUE THREAD

**Issue by NamISNaN** [mjjh1717/chatgpt-shuowen#12]
代码clone下来后，本地部署后端 如何实现打字机效果呢？已经把 api 文件夹下 proxy.js 的删除掉了 还需要有其他设置吗？

**Comment by hncboy** [comment]
> 代码clone下来后，本地部署后端 如何实现打字机效果呢？已经把 api 文件夹下 proxy.js 的删除掉了 还需要有其他设置吗？

IDEA 启动默认就是打字机效果，nginx 需要单独配置 https://github.com/hncboy/chatgpt-web-java/issues/71
