### ISSUE TITLE
用方式一配置了也不能流式输出呀

### ISSUE THREAD

**Issue by liusenlei** [mjjh1717/chatgpt-shuowen#13]
能不能告知一下nginx应该如何配置呢
location /api {
        rewrite  ^/api/?(.*)$ /$1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass 代理地址;
}

**Comment by mjjh1717** [comment]
方式一仅针对项目在vercel上部署的情况,服务器上nginx请参考后台历史中issue的回答

**Comment by liusenlei** [comment]
> 方法一仅针对项目在vercel上部的情况，服务器上nginx请参考后台历史中issue的回答
没有找到其他的issue回答呀

**Comment by liusenlei** [comment]
可以提供一下其他的issue吗

**Comment by hncboy** [comment]
> 

https://github.com/hncboy/chatgpt-web-java/issues/71
