### ISSUE TITLE
使用Nginx部署如何能实现打字的效果

### ISSUE THREAD

**Issue by 136750162** [mjjh1717/chatgpt-shuowen#16]
目前我用Nginx部署前端代码，给出的问题，都是等全部请求结束后，一次性出来回答的

**Comment by xw-mf** [comment]
> 目前我用Nginx部署前端代码，给出的问题，都是等全部请求结束后，一次性出来回答的

**Comment by hncboy** [comment]
https://github.com/hncboy/chatgpt-web-java/issues/71
