### ISSUE TITLE
按照命令执行报错

### ISSUE THREAD

**Issue by itxtl** [mjjh1717/chatgpt-shuowen#2]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/28883383/231030015-0406ebae-d9de-4f63-800c-ab53bdf5de41.png">

**Comment by mjjh1717** [comment]
试试 pnpm i 然后再pnpm bootstrap

**Comment by itxtl** [comment]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/28883383/231046428-5d79c49e-a888-4cf3-a00a-8c9ebda25f8a.png">
pnpm i 执行也报错，现在版本的不兼容的问题？

**Comment by itxtl** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/28883383/231047746-5f07097b-4f83-4446-90c2-81ace4539663.png">

我的三个版本分别是上吗这样的，电脑是 macbook m1 芯片，希望大佬帮忙看看～

**Comment by itxtl** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/28883383/231047801-03a7e50d-bbda-44de-9536-995a1b1c5096.png">

我的三个版本分别是上面这样的，电脑是 macbook m1 芯片，希望大佬帮忙看看～

**Comment by mjjh1717** [comment]
版本问题报错原因可能很多 可以参考这篇文章 https://blog.csdn.net/weixin_44803753/article/details/106184840  或者试着自己 fork https://github.com/Chanzhaoyu/chatgpt-web 原代码尝试，附上我的配置 我是win环境
![image](https://user-images.githubusercontent.com/56958167/231051070-48f65fd5-72a9-4f77-9786-b9b929947666.png)

**Comment by itxtl** [comment]
嗯嗯，谢谢，应该是版本的问题，我按照群里的消息将版本降低到 node 16就好了

**Comment by itxtl** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/28883383/231062443-77fd2d03-099b-477f-bd9e-616e2e164994.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/28883383/231062475-5978dbde-7177-4e55-8f12-69e6f4761c5f.png">
说文和解字都已经构建成功并运行了，但是说文报链接不上后端，前端都是使用 vscode 直接运行，后端使用idea
下面是说文的报错提示
<img width="593" alt="image" src="https://user-images.githubusercontent.com/28883383/231062639-5ba746da-f2ed-4cc4-8e0e-b384666b57ed.png">

**Comment by itxtl** [comment]
嗯，可以了，是前端默认的端口没有跟后端对应上。

**Comment by illsiveblue** [comment]
请问后端端口在哪配置，应该如何配置

**Comment by pl04079186** [comment]
部署后启动完毕，访问客户端，后端报错
cn.dev33.satoken.exception.NotLoginException: 未能读取到有效Token

**Comment by AllenLuosong** [comment]
同问，build构建之后，使用Ng维护静态页面，访问注册功能时前端页面一闪而过立即刷新到登录页面，后端提示NotLoginException: 未能读取到有效Token

**Comment by LYJSPEEDX** [comment]
解决了吗？我也是这个问题
