### ISSUE TITLE
右边聊天历史记录不能正确显示

### ISSUE THREAD

**Issue by PiPi0413** [mjjh1717/chatgpt-shuowen#21]
当创建两个图纸以后,切换图纸会发生该图纸聊天历史记录加载不出来的情况.在当前页面刷新,当前选中的图纸可以加载数据,再次切换图纸以后报错,不能正常加载数据.

**Comment by mjjh1717** [comment]
可以截图一下报错数据或者界面吗

**Comment by PiPi0413** [comment]
奇怪,今天测有没问题了,我后续再跟进

**Comment by mjjh1717** [comment]
好的,谢谢
