### ISSUE TITLE
包含代码时样式有问题

### ISSUE THREAD

**Issue by hncboy** [mjjh1717/chatgpt-shuowen#26]
![image](https://github.com/mjjh1717/chatgpt-shuowen/assets/27755574/d3f09f5d-3612-4cbc-85f1-39b6e21d9ed2)

**Comment by mjjh1717** [comment]
![image](https://github.com/mjjh1717/chatgpt-shuowen/assets/56958167/f0ca709c-0879-4ef4-8a80-9b650e5ef0c2)
