### ISSUE TITLE
执行 pnpm dev 命令 报错如下，请问如何解决

### ISSUE THREAD

**Issue by miaomiao-wzs** [mjjh1717/chatgpt-shuowen#4]
![image](https://user-images.githubusercontent.com/83069913/232479116-ec95cdf3-14f7-43dc-ac63-9c0cd0b23256.png)

**Comment by mjjh1717** [comment]
可以看一下你的环境配置,这些是参考的环境版本
![image](https://user-images.githubusercontent.com/56958167/232496444-ecc059f9-4fed-48ee-affc-34e6daee40a1.png)
确保环境与依赖安装正确

或者尝试修改一下这里的端口号 chagpt-shuowen\vite.config.ts
![image](https://user-images.githubusercontent.com/56958167/232497260-8a2fb84c-b7a9-4ab9-88b5-645b97e8e190.png)

**Comment by miaomiao-wzs** [comment]
修改端口号后已解决
