### ISSUE TITLE
如果不要服务端  应该如何部署

### ISSUE THREAD

**Issue by hieivip** [mjjh1717/chatgpt-shuowen#7]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/54146330/233990462-6e0972b4-c3a7-4265-a075-d036cf5c70ea.png">

**Comment by mjjh1717** [comment]
不要服务端是指,使用token的形式,吗, 现在这个项目不支持使用tonken的方式了,需要对应的服务端,如果需要可以尝试原项目的token形式部署

**Comment by hncboy** [comment]
项目非纯前端，需要服务端
